name: Build Leaf 1.19.4
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@main
      - name: Set up JDK
        uses: graalvm/setup-graalvm@main
        with:
          version: 22.3.1
          java-version: 19
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" applyPatches --stacktrace --no-daemon
      - name: Create ReobfPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" createReobfPaperclipJar --stacktrace --no-daemon
      - name: Rename Paperclip Jar
        run: mv build/libs/leaf-paperclip-1.19.4-R0.1-SNAPSHOT-reobf.jar ./leaf-1.19.4.jar
      - name: Upload Leaf
        uses: actions/upload-artifact@v3
        with:
          name: Leaf
          path: ./leaf-1.19.4.jar
      - name: Release Leaf
        if: github.ref_name == 'ver/1.19.4'
        uses: softprops/action-gh-release@master
        with:
          name: "Leaf 1.19.4"
          tag_name: "ver-1.19.4"
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: "./leaf-1.19.4.jar"
          prerelease: false
